name: JaCoCo Agent - Maven Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'

    - name: Validate Maven Wrapper
      run: mvn --version
      working-directory: JVM/jacoco/maven

    - name: Run Tests
      run: mvn test
      working-directory: JVM/jacoco/maven
      
    - name: Archive coverage data
      uses: actions/upload-artifact@v2
      with:
        name: maven-coverage-data-jacoco
        path: JVM/jacoco/maven/.qodana/code-coverage

    - name: Qodana Scan
      uses: JetBrains/qodana-action@main
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_MVN_JACOCO }}
      with:
        args: "-i,JVM/jacoco/maven,--linter,jetbrains/qodana-jvm:latest"
        pr-mode: false
